/**
 * Navigation surfaces: the concrete product surfaces rendered inside the
 * primary navigation areas. Each surface declares which matrix features it
 * makes discoverable, plus natural-language aliases for the universal
 * intent/command surface.
 *
 * The Explore surface is special: its card set is DERIVED from the complete
 * feature matrix (see surfaces/explore.ts), so it is intentionally not listed
 * with per-feature mappings here — discoverability must not be satisfied by
 * a single catch-all surface.
 */

import type { PrimaryNavAreaId } from "./navigation";

/** Identifier of a navigation surface. */
export type NavigationSurfaceId = string;

/** A concrete navigation surface inside a primary navigation area. */
export interface NavigationSurface {
  readonly id: NavigationSurfaceId;
  readonly navArea: PrimaryNavAreaId;
  /** Plain-language title shown to users (no internal vocabulary). */
  readonly title: string;
  readonly purpose: string;
  /** Matrix feature rows first discoverable on this surface. */
  readonly discovers: readonly string[];
  /** Natural-language requests the universal intent surface routes here. */
  readonly intentAliases: readonly string[];
}

/** The canonical surface registry. */
export const NAVIGATION_SURFACES: readonly NavigationSurface[] = [
  {
    id: "command-center-work-graph",
    navArea: "home-command-center",
    title: "Command Center",
    purpose: "Your business at a glance: goals, pending decisions, opportunities, simulations, alerts and connection health",
    discovers: [
      "global-merchant-agent",
      "goal-driven-operation",
      "persistent-merchant-memory",
      "goal-plan-simulate-approve-execute-verify-learn",
      "one-main-agent",
      "continuous-opportunity-discovery",
    ],
    intentAliases: ["what are we working on", "show pending decisions", "how is the business doing"],
  },
  {
    id: "buyer-intent-canvas",
    navArea: "buy-intent-canvas",
    title: "What do you need?",
    purpose: "Describe what you need in your own words; add constraints; compare plans including group deals, rentals and swaps",
    discovers: [
      "natural-language-shopping-intent",
      "intent-deadline",
      "intent-maximum-total-cost",
      "intent-quality",
      "intent-seller-credibility",
      "intent-privacy-security",
      "intent-speed",
      "intent-delivery-pickup",
      "intent-condition",
      "intent-substitutes",
      "intent-financing",
      "intent-buy-now-vs-wait",
      "intent-price-timing",
      "intent-local-commerce",
      "intent-group-buy",
      "intent-merchant-suggested-group-buy",
      "intent-negotiation",
      "intent-rent-borrow",
      "intent-resale",
      "intent-swap-trade",
      "intent-multi-hop-trade-cycles",
      "intent-proof-recourse-aware-execution",
    ],
    intentAliases: ["I need a", "find me", "I want to buy", "help me choose"],
  },
  {
    id: "storefront-studio",
    navArea: "sell-store",
    title: "Storefront",
    purpose: "Design your shop, its content and how customers check out and pay",
    discovers: ["storefront-themes-content", "cart-checkout-payments"],
    intentAliases: ["design my storefront", "set up checkout", "change my online shop"],
  },
  {
    id: "autonomous-store-config",
    navArea: "sell-store",
    title: "Store on Autopilot",
    purpose: "Let UNiCOM run day-to-day selling inside limits you set: margins, spending, refunds and stop conditions",
    discovers: ["autonomous-store", "autonomous-pricing-merchandising-replenishment-campaigns"],
    intentAliases: ["run my store for me", "automatic pricing", "autopilot my shop"],
  },
  {
    id: "operate-catalog",
    navArea: "operate",
    title: "Products & Pricing",
    purpose: "Manage products, variants, collections, prices, sales and coupons",
    discovers: ["catalog-products-variants-skus-collections", "pricing-promotions-coupons"],
    intentAliases: ["edit products", "change a price", "create a coupon"],
  },
  {
    id: "operate-inventory",
    navArea: "operate",
    title: "Inventory & Locations",
    purpose: "Track stock, receive deliveries, transfer between locations, forecast, and sell across channels",
    discovers: ["inventory-locations-transfers-receiving-forecasting", "multi-location-channel-commerce"],
    intentAliases: ["check stock", "receive a delivery", "transfer stock"],
  },
  {
    id: "operate-orders",
    navArea: "operate",
    title: "Orders & Fulfillment",
    purpose: "Orders, shipping, returns, exchanges and refunds",
    discovers: ["orders-fulfillment-returns-exchanges-refunds"],
    intentAliases: ["show orders", "process a return", "ship an order"],
  },
  {
    id: "operate-customers",
    navArea: "operate",
    title: "Customers",
    purpose: "Customer records, loyalty, subscriptions and communication history",
    discovers: ["customers-crm-loyalty-subscriptions"],
    intentAliases: ["show customers", "loyalty program", "subscriptions"],
  },
  {
    id: "operate-marketing-analytics",
    navArea: "operate",
    title: "Marketing & Reports",
    purpose: "Campaigns, analytics and business-to-business selling",
    discovers: ["marketing-analytics", "b2b"],
    intentAliases: ["run a campaign", "show reports", "B2B customers"],
  },
  {
    id: "operate-pos",
    navArea: "operate",
    title: "In-Person Selling",
    purpose: "Sell in person with registers and checkout hardware",
    discovers: ["pos", "physical-pos"],
    intentAliases: ["ring up a sale", "open the register", "in-person checkout"],
  },
  {
    id: "physical-commerce-tools",
    navArea: "operate",
    title: "Store Tools",
    purpose: "Scan barcodes, count stock, capture receipts, weigh items and photograph shelves",
    discovers: [
      "physical-barcode-scanners",
      "physical-phone-tablet-camera",
      "physical-qr",
      "physical-nfc",
      "physical-rfid",
      "physical-scanner-scales",
      "physical-ordinary-weighing-workflows",
      "physical-shelf-photos-computer-vision",
      "physical-cycle-counts",
      "physical-receipts-invoices",
    ],
    intentAliases: ["count stock", "scan a barcode", "capture a receipt"],
  },
  {
    id: "opportunity-inbox",
    navArea: "discover",
    title: "Opportunities",
    purpose: "Deals and ideas beyond today's task: sell what you own, group deals, swaps, discounts and smart waiting",
    discovers: [
      "user-resale-owned-items",
      "user-rental",
      "user-swaps",
      "user-group-buying",
      "user-discounts",
      "user-future-price-opportunities",
      "user-unused-subscriptions",
      "user-warranty-recovery",
      "user-local-pickup-shared-logistics",
      "user-other-proactive-opportunities",
      "opportunity-discovery",
      "group-buy-formation",
      "merchant-demand-generation-proposals",
      "bounded-multi-hop-trade",
      "privacy-aware-matching",
      "deadline-aware-waiting",
    ],
    intentAliases: ["any opportunities", "ways to save money", "what can I sell"],
  },
  {
    id: "live-commerce-discovery",
    navArea: "discover",
    title: "Live Shopping",
    purpose: "Watch, bid and buy inside live selling streams",
    discovers: ["live-streams", "whatnot-live-commerce"],
    intentAliases: ["live shopping", "watch a live sale", "bid on a stream"],
  },
  {
    id: "lab-surface",
    navArea: "lab",
    title: "Lab",
    purpose: "Test decisions safely: simulations, what-if scenarios, experiments and different ways of working",
    discovers: [
      "commerce-twin",
      "what-if-counterfactual-simulation",
      "causal-diagnosis",
      "supplier-optimization",
      "experimentation-canary-rollout",
      "agent-generated-business-tools",
      "strategy-search",
      "organization-search",
      "ephemeral-system-actors-delegates",
      "capability-based-actor-representation",
      "multi-objective-optimization",
      "system1-jepa-system2-routing",
    ],
    intentAliases: ["what if", "simulate a change", "run an experiment"],
  },
  {
    id: "trust-security-center",
    navArea: "trust-security",
    title: "Trust & Safety",
    purpose: "Who and what to trust, proof behind every deal, and active protection against fraud and abuse",
    discovers: [
      "separate-trust-kinds",
      "proof-p0-p5",
      "threat-fake-rigged-reviews",
      "threat-review-rings",
      "threat-counterfeit-product-substitution",
      "threat-wrong-item-shipments",
      "threat-false-non-delivery",
      "threat-false-wrong-item-claims",
      "threat-refund-return-abuse",
      "threat-account-agent-compromise",
      "threat-connector-compromise",
      "threat-prompt-injection",
      "threat-marketplace-collusion",
      "threat-sybil-identities",
      "threat-anomalous-agent-behavior",
      "security-pipeline-signal-to-learning",
    ],
    intentAliases: ["is this seller safe", "security alerts", "why do I trust this"],
  },
  {
    id: "connector-studio",
    navArea: "connections",
    title: "Connect Channels",
    purpose: "Connect marketplaces and channels — by API, files, or a controlled login when there is no API",
    discovers: [
      "push-pull-catalogs-prices-inventory-orders-permitted-customer-data",
      "shopify",
      "ebay",
      "amazon",
      "jumia",
      "depop",
      "ucp-acp-mcp-a2a-adapters",
      "api-sdk-rest-graphql",
      "webhooks",
      "cli",
      "csv-xml-edi-sftp-email",
      "browser-only-systems",
      "browser-sessions-isolated-authority",
      "live-streams",
    ],
    intentAliases: ["connect a channel", "connect Shopify", "add a marketplace"],
  },
  {
    id: "local-edge-setup",
    navArea: "connections",
    title: "Connect a Store Computer",
    purpose: "Connect cash registers, files, devices and networks in your shop — even without internet or an API",
    discovers: [
      "local-pos-no-api",
      "usb-serial-lan",
      "physical-edge",
      "physical-local-network",
      "physical-usb-serial",
      "physical-offline-edge-operation",
    ],
    intentAliases: ["connect my POS", "connect my cash register", "set up the store computer"],
  },
  {
    id: "app-extensions",
    navArea: "connections",
    title: "Apps & Skills",
    purpose: "Install apps and extensions, or ask for new ones to be built",
    discovers: ["app-extension-ecosystem", "ai-generated-apps-workflows", "skills"],
    intentAliases: ["install an app", "add a skill", "build me a tool"],
  },
  {
    id: "explore-capabilities",
    navArea: "explore-capabilities",
    title: "Explore",
    purpose: "Everything UNiCOM can do, grouped by what you want to achieve, each with a Try-it action",
    discovers: [],
    intentAliases: ["what can you do", "show me everything", "help me get started"],
  },
  {
    id: "workspace-settings",
    navArea: "settings",
    title: "Settings",
    purpose: "Workspace, roles and switching between buying, selling and other modes",
    discovers: [],
    intentAliases: ["settings", "switch to selling", "change my role"],
  },
  {
    id: "operator-console",
    navArea: "settings",
    title: "System & Data",
    purpose: "Where your data lives, how the platform is running, and what would change if you moved providers",
    discovers: [
      "deploy-edge-api",
      "deploy-durable-workflows",
      "deploy-async-queues",
      "deploy-realtime-coordination",
      "deploy-postgres",
      "deploy-object-evidence-storage",
      "deploy-cache",
      "deploy-browser-runtime",
      "deploy-local-merchant-edge",
      "deploy-model-gateway",
      "deploy-observability",
      "deploy-replaceable-compute-provider-adapters",
    ],
    intentAliases: ["where is my data", "system status", "can I move providers"],
  },
];
