/**
 * W2-010 — Verified incumbent product table, part 1 (class B).
 *
 * Split from persona-incumbent-verification.ts for the architecture
 * file-line budget; see that file for the evidence-class laws. Class B:
 * official interactive demo or authentic public interactive UI verified
 * publicly accessible via its official domain (web search, 2026-10-09; raw
 * snapshots in docs/simulations/results/baseline/adoption/
 * incumbent-verification-evidence.json). NO performance data captured.
 *
 * Internal to the @unicom/agent module.
 */

import { INCUMBENT_VERIFICATION_DATE, type VerifiedIncumbentProduct } from "./persona-types.js";

const SEARCHED = "official-domain-web-search" as const;

/** Class-B product entries: public interactive UI verified. */
export const VERIFIED_INCUMBENT_PRODUCTS_B: Readonly<
  Record<string, VerifiedIncumbentProduct>
> = {
  // --- Class B: official public interactive UI verified ------------------
  "amazon-business": {
    productKey: "amazon-business",
    label: "Amazon Business",
    evidenceClass: "B",
    officialDomains: ["business.amazon.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official business purchasing portal; public interactive UI with free business account registration.",
  },
  grainger: {
    productKey: "grainger",
    label: "Grainger",
    evidenceClass: "B",
    officialDomains: ["www.grainger.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official MRO industrial-supply catalog and ordering portal, publicly browsable.",
  },
  fastenal: {
    productKey: "fastenal",
    label: "Fastenal",
    evidenceClass: "B",
    officialDomains: ["www.fastenal.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official industrial and safety supplies ordering portal, publicly browsable.",
  },
  "united-rentals": {
    productKey: "united-rentals",
    label: "United Rentals",
    evidenceClass: "B",
    officialDomains: ["www.unitedrentals.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official equipment-rental site; public interactive rental catalog and branch locator.",
  },
  faire: {
    productKey: "faire",
    label: "Faire",
    evidenceClass: "B",
    officialDomains: ["www.faire.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official wholesale marketplace; public interactive browsing.",
  },
  alibaba: {
    productKey: "alibaba",
    label: "Alibaba.com",
    evidenceClass: "B",
    officialDomains: ["www.alibaba.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official B2B wholesale marketplace; public interactive browsing.",
  },
  cdw: {
    productKey: "cdw",
    label: "CDW",
    evidenceClass: "B",
    officialDomains: ["www.cdw.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official IT products and services business purchasing catalog, publicly browsable.",
  },
  shi: {
    productKey: "shi",
    label: "SHI International",
    evidenceClass: "B",
    officialDomains: ["www.shi.com", "portal.shi.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official IT solutions business catalog and account portal; public catalog browsing.",
  },
  medline: {
    productKey: "medline",
    label: "Medline",
    evidenceClass: "B",
    officialDomains: ["www.medline.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official medical products catalog; public shop-category browsing (300k+ products).",
  },
  fleetpride: {
    productKey: "fleetpride",
    label: "FleetPride",
    evidenceClass: "B",
    officialDomains: ["www.fleetpride.com", "branches.fleetpride.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official heavy-duty truck parts e-commerce and branch locator, publicly browsable.",
  },
  napa: {
    productKey: "napa",
    label: "NAPA Auto Parts",
    evidenceClass: "B",
    officialDomains: ["www.napaonline.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official online auto-parts shopping site, publicly browsable.",
  },
  penske: {
    productKey: "penske",
    label: "Penske Truck Rental",
    evidenceClass: "B",
    officialDomains: ["www.pensketruckrental.com", "www.gopenske.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official public interactive truck-rental booking and quote site. Upgraded from the frozen C default after public interactive UI was verified.",
  },
  ryder: {
    productKey: "ryder",
    label: "Ryder",
    evidenceClass: "B",
    officialDomains: ["www.ryder.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official public rental and fleet site with interactive quote flows. Upgraded from the frozen C default after public interactive UI was verified.",
  },
  "restaurant-depot": {
    productKey: "restaurant-depot",
    label: "Restaurant Depot",
    evidenceClass: "B",
    officialDomains: ["www.restaurantdepot.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official wholesale cash-and-carry site with public in-store product viewing.",
  },
  square: {
    productKey: "square",
    label: "Square",
    evidenceClass: "B",
    officialDomains: ["squareup.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official POS platform site; public interactive product and pricing UI.",
  },
  shopify: {
    productKey: "shopify",
    label: "Shopify",
    evidenceClass: "B",
    officialDomains: ["www.shopify.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official commerce platform site with public storefront demos and free trial.",
  },
  ebay: {
    productKey: "ebay",
    label: "eBay",
    evidenceClass: "B",
    officialDomains: ["www.ebay.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official public marketplace; interactive browsing and listings.",
  },
  depop: {
    productKey: "depop",
    label: "Depop",
    evidenceClass: "B",
    officialDomains: ["www.depop.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official public fashion resale marketplace.",
  },
  poshmark: {
    productKey: "poshmark",
    label: "Poshmark",
    evidenceClass: "B",
    officialDomains: ["poshmark.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official public social resale marketplace.",
  },
  sharegrid: {
    productKey: "sharegrid",
    label: "ShareGrid",
    evidenceClass: "B",
    officialDomains: ["www.sharegrid.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official public equipment-rental marketplace.",
  },
  kitsplit: {
    productKey: "kitsplit",
    label: "KitSplit",
    evidenceClass: "B",
    officialDomains: ["kitsplit.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official public camera-equipment rental marketplace.",
  },
  "gsa-advantage": {
    productKey: "gsa-advantage",
    label: "GSA Advantage",
    evidenceClass: "B",
    officialDomains: ["www.gsaglobalsupply.gsa.gov", "buy.gsa.gov"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official online shopping and ordering system for authorized unclassified procurement; public browsing.",
  },
  thomasnet: {
    productKey: "thomasnet",
    label: "Thomasnet",
    evidenceClass: "B",
    officialDomains: ["www.thomasnet.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official public supplier-discovery and sourcing platform.",
  },
  xometry: {
    productKey: "xometry",
    label: "Xometry",
    evidenceClass: "B",
    officialDomains: ["www.xometry.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official public on-demand manufacturing quote platform.",
  },
  mcmaster: {
    productKey: "mcmaster",
    label: "McMaster-Carr",
    evidenceClass: "B",
    officialDomains: ["www.mcmaster.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official public hardware/components catalog and ordering site.",
  },
  instacart: {
    productKey: "instacart",
    label: "Instacart",
    evidenceClass: "B",
    officialDomains: ["www.instacart.com", "shoppers.instacart.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official public shopper ordering platform.",
  },
  "staples-advantage": {
    productKey: "staples-advantage",
    label: "Staples Business Advantage",
    evidenceClass: "B",
    officialDomains: ["www.staplesadvantage.com"],
    verification: SEARCHED,
    verifiedAt: INCUMBENT_VERIFICATION_DATE,
    note: "Official B2B office-supplies site with public shop browsing and free business account. Upgraded from the frozen C default after public interactive UI was verified.",
  },
};
