/**
 * W1-009 portfolio — per-industry project-template DATA (group 3 of 4).
 *
 * Industries: fashion-apparel-retail-brands, entertainment-media-production,
 * legal-professional-services.
 */
import type { TemplateSeed } from "./templates-data-1.js";

export const TEMPLATES_GROUP_3: Readonly<Record<string, readonly TemplateSeed[]>> = {
  "fashion-apparel-retail-brands": [
    {
      templateId: "trims-procurement",
      title: "Trims procurement (buttons + zippers + labels)",
      commerceScope: "supplier-trims-procurement",
      lines: [
        { lineId: "L01", sku: "sku-button-12mm", description: "12mm buttons (card of 100)", basePriceMinor: 350, currency: "USD", quantityMode: "COUNT", baseQuantity: 100, substitutes: ["sku-button-14mm"], evidenceRequired: "P1" },
        { lineId: "L02", sku: "sku-zipper-25cm", description: "25cm zipper", basePriceMinor: 180, currency: "USD", quantityMode: "COUNT", baseQuantity: 500, substitutes: [], evidenceRequired: "P0" },
        { lineId: "L03", sku: "sku-label-woven", description: "Woven label (roll of 1000)", basePriceMinor: 950, currency: "USD", quantityMode: "COUNT", baseQuantity: 20, substitutes: [], evidenceRequired: "P1" },
      ],
      baseBudgetMinor: 125000,
      budgetCurrency: "USD",
      hardDeadlineDays: 30,
      softDeadlineDays: 21,
      qualityDimension: "GRADE",
      qualityMin: "A",
      deliveryMode: "SHIP_TO_LOCATION",
      deliveryLocationPrefix: "loc-factory",
      returnsAllowed: true,
      returnsWindowDays: 30,
      returnsRecourse: "CREDIT",
      evidenceRequired: ["PO", "DELIVERY_RECEIPT", "INVOICE"],
      approvalMaxAmountMinor: 50000,
    },
    {
      templateId: "resale-consignment-batch",
      title: "Resale + consignment batch (returned inventory)",
      commerceScope: "rental-resale-consignment",
      lines: [
        { lineId: "L01", sku: "sku-returns-batch", description: "Returns batch (graded)", basePriceMinor: 12500, currency: "USD", quantityMode: "COUNT", baseQuantity: 80, substitutes: [], evidenceRequired: "P2" },
        { lineId: "L02", sku: "sku-consignment-slot", description: "Consignment slot monthly", basePriceMinor: 4500, currency: "USD", quantityMode: "COUNT", baseQuantity: 6, substitutes: [], evidenceRequired: "P2" },
      ],
      baseBudgetMinor: 350000,
      budgetCurrency: "USD",
      hardDeadlineDays: 45,
      softDeadlineDays: 30,
      qualityDimension: "GRADE",
      qualityMin: "B",
      deliveryMode: "SHIP_TO_LOCATION",
      deliveryLocationPrefix: "loc-warehouse",
      returnsAllowed: true,
      returnsWindowDays: 60,
      returnsRecourse: "CREDIT",
      evidenceRequired: ["CONSIGNMENT_AGREEMENT", "DELIVERY_RECEIPT", "INVOICE"],
      approvalMaxAmountMinor: 100000,
    },
  ],
  "entertainment-media-production": [
    {
      templateId: "equipment-rental-batch",
      title: "Production equipment rental (camera + audio + lighting)",
      commerceScope: "buy-vs-rent-equipment",
      lines: [
        { lineId: "L01", sku: "sku-camera-cinema-rental", description: "Cinema camera weekly rental", basePriceMinor: 250000, currency: "USD", quantityMode: "COUNT", baseQuantity: 2, substitutes: [], evidenceRequired: "P2" },
        { lineId: "L02", sku: "sku-audio-mixer-rental", description: "Audio mixer weekly rental", basePriceMinor: 85000, currency: "USD", quantityMode: "COUNT", baseQuantity: 1, substitutes: [], evidenceRequired: "P2" },
        { lineId: "L03", sku: "sku-lighting-kit-rental", description: "Lighting kit weekly rental", basePriceMinor: 65000, currency: "USD", quantityMode: "COUNT", baseQuantity: 2, substitutes: [], evidenceRequired: "P1" },
      ],
      baseBudgetMinor: 950000,
      budgetCurrency: "USD",
      hardDeadlineDays: 14,
      softDeadlineDays: 7,
      qualityDimension: "CONDITION",
      qualityMin: "A",
      deliveryMode: "SITE_DELIVERY",
      deliveryLocationPrefix: "loc-set",
      returnsAllowed: true,
      returnsWindowDays: 3,
      returnsRecourse: "REPLACEMENT",
      evidenceRequired: ["RENTAL_AGREEMENT", "DELIVERY_RECEIPT"],
      approvalMaxAmountMinor: 250000,
    },
    {
      templateId: "merchandise-catalog-order",
      title: "Merchandise catalog order (event T-shirts + posters)",
      commerceScope: "merchandise-catalog-orders",
      lines: [
        { lineId: "L01", sku: "sku-tee-event", description: "Event T-shirt", basePriceMinor: 1250, currency: "USD", quantityMode: "COUNT", baseQuantity: 500, substitutes: [], evidenceRequired: "P1" },
        { lineId: "L02", sku: "sku-poster-a2", description: "A2 poster", basePriceMinor: 450, currency: "USD", quantityMode: "COUNT", baseQuantity: 200, substitutes: [], evidenceRequired: "P0" },
      ],
      baseBudgetMinor: 95000,
      budgetCurrency: "USD",
      hardDeadlineDays: 21,
      softDeadlineDays: 14,
      qualityDimension: "GRADE",
      qualityMin: "A",
      deliveryMode: "SHIP_TO_LOCATION",
      deliveryLocationPrefix: "loc-warehouse",
      returnsAllowed: true,
      returnsWindowDays: 30,
      returnsRecourse: "CREDIT",
      evidenceRequired: ["PO", "DELIVERY_RECEIPT", "INVOICE"],
      approvalMaxAmountMinor: 50000,
    },
  ],
  "legal-professional-services": [
    {
      templateId: "office-supplies-quarterly",
      title: "Office supplies quarterly procurement",
      commerceScope: "office-equipment-subscriptions-bulk-rental-recourse",
      lines: [
        { lineId: "L01", sku: "sku-paper-a4", description: "A4 paper (5000 sheets)", basePriceMinor: 4500, currency: "USD", quantityMode: "COUNT", baseQuantity: 30, substitutes: [], evidenceRequired: "P1" },
        { lineId: "L02", sku: "sku-toner-laserjet", description: "Toner cartridge", basePriceMinor: 8900, currency: "USD", quantityMode: "COUNT", baseQuantity: 12, substitutes: [], evidenceRequired: "P1" },
      ],
      baseBudgetMinor: 250000,
      budgetCurrency: "USD",
      hardDeadlineDays: 14,
      softDeadlineDays: 10,
      qualityDimension: "GRADE",
      qualityMin: "B",
      deliveryMode: "SHIP_TO_LOCATION",
      deliveryLocationPrefix: "loc-office",
      returnsAllowed: true,
      returnsWindowDays: 30,
      returnsRecourse: "CREDIT",
      evidenceRequired: ["PO", "DELIVERY_RECEIPT", "INVOICE"],
      approvalMaxAmountMinor: 50000,
    },
    {
      templateId: "expert-vendor-sourcing",
      title: "External expert/vendor sourcing + procurement",
      commerceScope: "external-expert-vendor-sourcing",
      lines: [
        { lineId: "L01", sku: "sku-expert-consult-day", description: "Expert consultant day rate", basePriceMinor: 25000, currency: "USD", quantityMode: "COUNT", baseQuantity: 5, substitutes: [], evidenceRequired: "P3" },
        { lineId: "L02", sku: "sku-research-license", description: "Research database license", basePriceMinor: 45000, currency: "USD", quantityMode: "COUNT", baseQuantity: 1, substitutes: [], evidenceRequired: "P2" },
      ],
      baseBudgetMinor: 350000,
      budgetCurrency: "USD",
      hardDeadlineDays: 30,
      softDeadlineDays: 21,
      qualityDimension: "GRADE",
      qualityMin: "A",
      deliveryMode: "SHIP_TO_LOCATION",
      deliveryLocationPrefix: "loc-office",
      returnsAllowed: false,
      returnsWindowDays: 0,
      returnsRecourse: "NONE",
      evidenceRequired: ["CONTRACT", "INVOICE"],
      approvalMaxAmountMinor: 100000,
    },
  ],
};
