/**
 * W1-009 portfolio — per-industry project-template DATA (group 4 of 4).
 *
 * Industries: defense-security-government-contracting,
 * manufacturing-supply-chain, supermarkets-local-retail (no-RFID mandatory).
 */
import type { TemplateSeed } from "./templates-data-1.js";

export const TEMPLATES_GROUP_4: Readonly<Record<string, readonly TemplateSeed[]>> = {
  "defense-security-government-contracting": [
    {
      templateId: "compliant-supply-sourcing",
      title: "Compliant unclassified supply sourcing",
      commerceScope: "compliant-unclassified-supply-sourcing-purchase-authorization",
      lines: [
        { lineId: "L01", sku: "sku-tool-set", description: "Tool set (compliant)", basePriceMinor: 18500, currency: "USD", quantityMode: "COUNT", baseQuantity: 15, substitutes: [], evidenceRequired: "P2" },
        { lineId: "L02", sku: "sku-ppe-kit", description: "PPE kit", basePriceMinor: 8900, currency: "USD", quantityMode: "COUNT", baseQuantity: 50, substitutes: [], evidenceRequired: "P2" },
      ],
      baseBudgetMinor: 950000,
      budgetCurrency: "USD",
      hardDeadlineDays: 60,
      softDeadlineDays: 45,
      qualityDimension: "GRADE",
      qualityMin: "MIL-SPEC",
      deliveryMode: "SHIP_TO_LOCATION",
      deliveryLocationPrefix: "loc-base",
      returnsAllowed: true,
      returnsWindowDays: 30,
      returnsRecourse: "CREDIT",
      evidenceRequired: ["PO", "DELIVERY_RECEIPT", "INVOICE", "AUTHORIZATION"],
      approvalMaxAmountMinor: 250000,
    },
    {
      templateId: "equipment-rental-compliant",
      title: "Compliant equipment rental (vehicles + generators)",
      commerceScope: "compliant-equipment-rental",
      lines: [
        { lineId: "L01", sku: "sku-vehicle-rental-weekly", description: "Vehicle weekly rental (compliant)", basePriceMinor: 145000, currency: "USD", quantityMode: "COUNT", baseQuantity: 4, substitutes: [], evidenceRequired: "P2" },
        { lineId: "L02", sku: "sku-generator-rental", description: "Generator weekly rental", basePriceMinor: 95000, currency: "USD", quantityMode: "COUNT", baseQuantity: 2, substitutes: [], evidenceRequired: "P2" },
      ],
      baseBudgetMinor: 950000,
      budgetCurrency: "USD",
      hardDeadlineDays: 30,
      softDeadlineDays: 21,
      qualityDimension: "GRADE",
      qualityMin: "MIL-SPEC",
      deliveryMode: "SITE_DELIVERY",
      deliveryLocationPrefix: "loc-base",
      returnsAllowed: true,
      returnsWindowDays: 14,
      returnsRecourse: "REPLACEMENT",
      evidenceRequired: ["RENTAL_AGREEMENT", "DELIVERY_RECEIPT", "AUTHORIZATION"],
      approvalMaxAmountMinor: 250000,
    },
  ],
  "manufacturing-supply-chain": [
    {
      templateId: "bom-component-sourcing",
      title: "BOM component sourcing (multi-supplier quote)",
      commerceScope: "bom-component-sourcing-receiving-lot-serial-multi-site",
      lines: [
        { lineId: "L01", sku: "sku-resistor-10k", description: "Resistor 10kΩ (reel of 5000)", basePriceMinor: 2500, currency: "USD", quantityMode: "COUNT", baseQuantity: 50, substitutes: ["sku-resistor-10k-alt"], evidenceRequired: "P2" },
        { lineId: "L02", sku: "sku-capacitor-100uf", description: "Capacitor 100µF", basePriceMinor: 850, currency: "USD", quantityMode: "COUNT", baseQuantity: 200, substitutes: [], evidenceRequired: "P1" },
        { lineId: "L03", sku: "sku-pcb-blank", description: "PCB blank", basePriceMinor: 4200, currency: "USD", quantityMode: "COUNT", baseQuantity: 100, substitutes: [], evidenceRequired: "P2" },
      ],
      baseBudgetMinor: 950000,
      budgetCurrency: "USD",
      hardDeadlineDays: 30,
      softDeadlineDays: 21,
      qualityDimension: "GRADE",
      qualityMin: "INDUSTRIAL",
      deliveryMode: "SHIP_TO_LOCATION",
      deliveryLocationPrefix: "loc-plant",
      returnsAllowed: true,
      returnsWindowDays: 30,
      returnsRecourse: "CREDIT",
      evidenceRequired: ["PO", "DELIVERY_RECEIPT", "INVOICE", "LOT_SERIAL"],
      approvalMaxAmountMinor: 100000,
    },
    {
      templateId: "tooling-rental-vs-buy",
      title: "Tooling rental vs purchase (CNC fixture + jig)",
      commerceScope: "rental-vs-purchase-of-tooling",
      lines: [
        { lineId: "L01", sku: "sku-cnc-fixture-rental", description: "CNC fixture monthly rental", basePriceMinor: 120000, currency: "USD", quantityMode: "COUNT", baseQuantity: 3, substitutes: [], evidenceRequired: "P2" },
        { lineId: "L02", sku: "sku-jig-custom", description: "Custom jig", basePriceMinor: 45000, currency: "USD", quantityMode: "COUNT", baseQuantity: 4, substitutes: [], evidenceRequired: "P2" },
      ],
      baseBudgetMinor: 550000,
      budgetCurrency: "USD",
      hardDeadlineDays: 21,
      softDeadlineDays: 14,
      qualityDimension: "GRADE",
      qualityMin: "INDUSTRIAL",
      deliveryMode: "SHIP_TO_LOCATION",
      deliveryLocationPrefix: "loc-plant",
      returnsAllowed: true,
      returnsWindowDays: 14,
      returnsRecourse: "REPLACEMENT",
      evidenceRequired: ["RENTAL_AGREEMENT", "DELIVERY_RECEIPT"],
      approvalMaxAmountMinor: 150000,
    },
  ],
  "supermarkets-local-retail": [
    {
      templateId: "supplier-po-receiving",
      title: "Supplier PO + receiving (with weighted goods + barcode count)",
      commerceScope: "catalog-pos-supplier-ordering-weighted-reconciliation-no-rfid",
      lines: [
        { lineId: "L01", sku: "sku-milk-1l", description: "Milk 1L", basePriceMinor: 199, currency: "USD", quantityMode: "COUNT", baseQuantity: 200, substitutes: ["sku-milk-2l"], evidenceRequired: "P1" },
        { lineId: "L02", sku: "sku-bananas", description: "Bananas (weighted)", basePriceMinor: 99, currency: "USD", quantityMode: "MEASURED", quantityUom: "KG", baseQuantity: 80, substitutes: [], evidenceRequired: "P1" },
        { lineId: "L03", sku: "sku-bread-loaf", description: "Bread loaf", basePriceMinor: 350, currency: "USD", quantityMode: "COUNT", baseQuantity: 150, substitutes: ["sku-bread-alt"], evidenceRequired: "P1" },
      ],
      baseBudgetMinor: 95000,
      budgetCurrency: "USD",
      hardDeadlineDays: 7,
      softDeadlineDays: 5,
      qualityDimension: "FRESHNESS",
      qualityMin: "A",
      deliveryMode: "SITE_DELIVERY",
      deliveryLocationPrefix: "loc-store",
      returnsAllowed: true,
      returnsWindowDays: 3,
      returnsRecourse: "CREDIT",
      evidenceRequired: ["PO", "DELIVERY_RECEIPT", "INVOICE"],
      approvalMaxAmountMinor: 25000,
    },
    {
      templateId: "no-rfid-reconciliation-day",
      title: "No-RFID supermarket day (POS sync + barcode count + weighted + reconciliation)",
      commerceScope: "no-rfid-supermarket-reconciliation",
      lines: [
        { lineId: "L01", sku: "sku-milk-1l", description: "Milk 1L", basePriceMinor: 199, currency: "USD", quantityMode: "COUNT", baseQuantity: 200, substitutes: [], evidenceRequired: "P1" },
        { lineId: "L02", sku: "sku-bananas", description: "Bananas (weighted)", basePriceMinor: 99, currency: "USD", quantityMode: "MEASURED", quantityUom: "KG", baseQuantity: 80, substitutes: [], evidenceRequired: "P1" },
        { lineId: "L03", sku: "sku-tomato-vine", description: "Vine tomatoes (weighted)", basePriceMinor: 299, currency: "USD", quantityMode: "MEASURED", quantityUom: "KG", baseQuantity: 40, substitutes: [], evidenceRequired: "P1" },
      ],
      baseBudgetMinor: 95000,
      budgetCurrency: "USD",
      hardDeadlineDays: 1,
      softDeadlineDays: 1,
      qualityDimension: "FRESHNESS",
      qualityMin: "A",
      deliveryMode: "LOCAL_EDGE",
      deliveryLocationPrefix: "loc-store",
      returnsAllowed: true,
      returnsWindowDays: 1,
      returnsRecourse: "CREDIT",
      evidenceRequired: ["PO", "POS_RECEIPT", "COUNT_OBSERVATION", "RECONCILIATION_RECORD"],
      approvalMaxAmountMinor: 25000,
    },
    {
      templateId: "expiry-recall-purchasing",
      title: "Expiry/recall purchasing hold + replacement",
      commerceScope: "expiry-recall-purchasing",
      lines: [
        { lineId: "L01", sku: "sku-yogurt-expired", description: "Yogurt (expiring)", basePriceMinor: 0, currency: "USD", quantityMode: "COUNT", baseQuantity: 0, substitutes: ["sku-yogurt-fresh"], evidenceRequired: "P1" },
        { lineId: "L02", sku: "sku-yogurt-fresh", description: "Yogurt fresh replacement", basePriceMinor: 150, currency: "USD", quantityMode: "COUNT", baseQuantity: 100, substitutes: [], evidenceRequired: "P1" },
      ],
      baseBudgetMinor: 25000,
      budgetCurrency: "USD",
      hardDeadlineDays: 1,
      softDeadlineDays: 1,
      qualityDimension: "FRESHNESS",
      qualityMin: "A",
      deliveryMode: "LOCAL_EDGE",
      deliveryLocationPrefix: "loc-store",
      returnsAllowed: true,
      returnsWindowDays: 1,
      returnsRecourse: "CREDIT",
      evidenceRequired: ["RECALL_NOTICE", "PO", "DELIVERY_RECEIPT"],
      approvalMaxAmountMinor: 10000,
    },
  ],
};
