/**
 * W1-009 portfolio — per-industry project-template DATA (group 2 of 4).
 *
 * Industries: healthcare-organizations, transportation-delivery,
 * hospitality-restaurants-hotels.
 */
import type { TemplateSeed } from "./templates-data-1.js";

export const TEMPLATES_GROUP_2: Readonly<Record<string, readonly TemplateSeed[]>> = {
  "healthcare-organizations": [
    {
      templateId: "medical-supplies-restock",
      title: "Medical supplies restock (gloves + syringes + gauze)",
      commerceScope: "medical-supplies-equipment-procurement-recall-holds",
      lines: [
        { lineId: "L01", sku: "sku-gloves-nitrile", description: "Nitrile gloves (box of 100)", basePriceMinor: 850, currency: "USD", quantityMode: "COUNT", baseQuantity: 500, substitutes: ["sku-gloves-latex"], evidenceRequired: "P2" },
        { lineId: "L02", sku: "sku-syringes-10ml", description: "10ml syringes (case of 100)", basePriceMinor: 3200, currency: "USD", quantityMode: "COUNT", baseQuantity: 80, substitutes: [], evidenceRequired: "P2" },
        { lineId: "L03", sku: "sku-gauze-4x4", description: "Gauze 4×4 (case of 200)", basePriceMinor: 2100, currency: "USD", quantityMode: "COUNT", baseQuantity: 60, substitutes: [], evidenceRequired: "P1" },
      ],
      baseBudgetMinor: 950000,
      budgetCurrency: "USD",
      hardDeadlineDays: 14,
      softDeadlineDays: 10,
      qualityDimension: "GRADE",
      qualityMin: "MEDICAL",
      deliveryMode: "SHIP_TO_LOCATION",
      deliveryLocationPrefix: "loc-clinic",
      returnsAllowed: true,
      returnsWindowDays: 30,
      returnsRecourse: "CREDIT",
      evidenceRequired: ["PO", "DELIVERY_RECEIPT", "INVOICE", "LOT_SERIAL"],
      approvalMaxAmountMinor: 100000,
    },
    {
      templateId: "recall-hold-procurement",
      title: "Recall-related purchasing hold + alternate sourcing",
      commerceScope: "recall-related-purchasing-holds",
      lines: [
        { lineId: "L01", sku: "sku-iv-set-recalled", description: "IV set (recalled)", basePriceMinor: 0, currency: "USD", quantityMode: "COUNT", baseQuantity: 0, substitutes: ["sku-iv-set-v2"], evidenceRequired: "P3" },
        { lineId: "L02", sku: "sku-iv-set-v2", description: "IV set replacement", basePriceMinor: 5400, currency: "USD", quantityMode: "COUNT", baseQuantity: 120, substitutes: [], evidenceRequired: "P2" },
      ],
      baseBudgetMinor: 750000,
      budgetCurrency: "USD",
      hardDeadlineDays: 7,
      softDeadlineDays: 5,
      qualityDimension: "GRADE",
      qualityMin: "MEDICAL",
      deliveryMode: "SHIP_TO_LOCATION",
      deliveryLocationPrefix: "loc-clinic",
      returnsAllowed: true,
      returnsWindowDays: 30,
      returnsRecourse: "CREDIT",
      evidenceRequired: ["RECALL_NOTICE", "PO", "DELIVERY_RECEIPT", "INVOICE"],
      approvalMaxAmountMinor: 100000,
    },
  ],
  "transportation-delivery": [
    {
      templateId: "fleet-parts-procurement",
      title: "Fleet parts procurement (tires + filters + oil)",
      commerceScope: "fleet-parts-tires-fuel-rental-vs-buy",
      lines: [
        { lineId: "L01", sku: "sku-tire-225-65r17", description: "Tire 225/65R17", basePriceMinor: 14500, currency: "USD", quantityMode: "COUNT", baseQuantity: 80, substitutes: ["sku-tire-225-65r17-alt"], evidenceRequired: "P1" },
        { lineId: "L02", sku: "sku-oil-filter", description: "Oil filter", basePriceMinor: 850, currency: "USD", quantityMode: "COUNT", baseQuantity: 200, substitutes: [], evidenceRequired: "P0" },
        { lineId: "L03", sku: "sku-engine-oil-5w30", description: "Engine oil 5W-30 (5qt)", basePriceMinor: 3200, currency: "USD", quantityMode: "COUNT", baseQuantity: 100, substitutes: ["sku-engine-oil-0w20"], evidenceRequired: "P1" },
      ],
      baseBudgetMinor: 1500000,
      budgetCurrency: "USD",
      hardDeadlineDays: 14,
      softDeadlineDays: 10,
      qualityDimension: "GRADE",
      qualityMin: "OE",
      deliveryMode: "PICKUP",
      deliveryLocationPrefix: "loc-depot",
      returnsAllowed: true,
      returnsWindowDays: 30,
      returnsRecourse: "CREDIT",
      evidenceRequired: ["PO", "DELIVERY_RECEIPT", "INVOICE"],
      approvalMaxAmountMinor: 100000,
    },
    {
      templateId: "equipment-rental-vs-buy",
      title: "Equipment rental vs purchase (lift + diagnostic)",
      commerceScope: "rental-vs-purchase",
      lines: [
        { lineId: "L01", sku: "sku-lift-2t-rental", description: "2t lift weekly rental", basePriceMinor: 85000, currency: "USD", quantityMode: "COUNT", baseQuantity: 4, substitutes: [], evidenceRequired: "P2" },
        { lineId: "L02", sku: "sku-diagnostic-scan", description: "Diagnostic scanner", basePriceMinor: 320000, currency: "USD", quantityMode: "COUNT", baseQuantity: 1, substitutes: [], evidenceRequired: "P2" },
      ],
      baseBudgetMinor: 700000,
      budgetCurrency: "USD",
      hardDeadlineDays: 21,
      softDeadlineDays: 14,
      qualityDimension: "GRADE",
      qualityMin: "B",
      deliveryMode: "SITE_DELIVERY",
      deliveryLocationPrefix: "loc-depot",
      returnsAllowed: true,
      returnsWindowDays: 14,
      returnsRecourse: "REPLACEMENT",
      evidenceRequired: ["RENTAL_AGREEMENT", "DELIVERY_RECEIPT"],
      approvalMaxAmountMinor: 200000,
    },
  ],
  "hospitality-restaurants-hotels": [
    {
      templateId: "food-supplies-order",
      title: "Food supplies weekly order (with weighted goods)",
      commerceScope: "food-beverage-linen-supplier-ordering-pos",
      lines: [
        { lineId: "L01", sku: "sku-tomato-roma", description: "Roma tomatoes (weighted)", basePriceMinor: 199, currency: "USD", quantityMode: "MEASURED", quantityUom: "KG", baseQuantity: 40, substitutes: ["sku-tomato-vine"], evidenceRequired: "P1" },
        { lineId: "L02", sku: "sku-flour-25kg", description: "Flour 25kg bag", basePriceMinor: 1850, currency: "USD", quantityMode: "COUNT", baseQuantity: 30, substitutes: [], evidenceRequired: "P1" },
        { lineId: "L03", sku: "sku-chicken-breast", description: "Chicken breast (weighted)", basePriceMinor: 499, currency: "USD", quantityMode: "MEASURED", quantityUom: "KG", baseQuantity: 25, substitutes: ["sku-chicken-thigh"], evidenceRequired: "P2" },
      ],
      baseBudgetMinor: 95000,
      budgetCurrency: "USD",
      hardDeadlineDays: 7,
      softDeadlineDays: 5,
      qualityDimension: "FRESHNESS",
      qualityMin: "A",
      deliveryMode: "SITE_DELIVERY",
      deliveryLocationPrefix: "loc-restaurant",
      returnsAllowed: true,
      returnsWindowDays: 2,
      returnsRecourse: "CREDIT",
      evidenceRequired: ["PO", "DELIVERY_RECEIPT", "INVOICE"],
      approvalMaxAmountMinor: 25000,
    },
    {
      templateId: "event-group-buy",
      title: "Banquet event group-buy (linens + cutlery)",
      commerceScope: "event-group-buy",
      lines: [
        { lineId: "L01", sku: "sku-linen-tablecloth", description: "Tablecloth", basePriceMinor: 850, currency: "USD", quantityMode: "COUNT", baseQuantity: 200, substitutes: [], evidenceRequired: "P1" },
        { lineId: "L02", sku: "sku-cutlery-set", description: "Cutlery set (case of 24)", basePriceMinor: 4200, currency: "USD", quantityMode: "COUNT", baseQuantity: 25, substitutes: [], evidenceRequired: "P1" },
      ],
      baseBudgetMinor: 250000,
      budgetCurrency: "USD",
      hardDeadlineDays: 14,
      softDeadlineDays: 10,
      qualityDimension: "GRADE",
      qualityMin: "A",
      deliveryMode: "SITE_DELIVERY",
      deliveryLocationPrefix: "loc-venue",
      returnsAllowed: true,
      returnsWindowDays: 7,
      returnsRecourse: "CREDIT",
      evidenceRequired: ["PO", "DELIVERY_RECEIPT", "INVOICE"],
      approvalMaxAmountMinor: 50000,
    },
  ],
};
